global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

rule_files:
  - alert.rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: ap-south-1
        access_key: <acc-key>
        secret_key: <sec-key>
        port: 9100
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - source_labels: [instance_id]
        target_label: hostname
        replacement: '${__address__}'
      - source_labels: [__meta_ec2_private_ip]
        target_label: instance

