route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 60s
  repeat_interval: 15m
  receiver: 'PromeAlerts'
receivers:
    - name: 'PromeAlerts'
      webhook_configs:
      - send_resolved: true
        url: 'http://127.0.0.1:6000/dispatch'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
