route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-alerts'
receivers:
- name: 'email-alerts'
  email_configs:
  - to: 'engineer@company.xyz'
    from: 'mymail@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: "mymail@gmail.com"
    auth_identity: "mymail@gmail.com"
    auth_password: app-password
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
