{
 "title": "Website-monitoring",
 "description": "A dashboard that monitors the Blackbox-exporter for Website monitoring.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "URL",
    "query": {
     "query": "label_values(probe_duration_seconds{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(probe_success,job)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview/Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Probed Sites",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_version{job=\"blackbox\"})"
    }
   ]
  },
  {
   "title": "Probes SSL Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(probe_http_ssl{job=\"blackbox\"} == 1) / count(probe_http_version{job=\"blackbox\"})"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{job=\"blackbox\"})"
    }
   ]
  },
  {
   "title": "Versions HTTP",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"http_version\", probe_http_version{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{http_version}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Codes HTTP",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"value\", probe_http_status_code{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Probe Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=~\"$job\"} == 1)"
    }
   ]
  },
  {
   "title": "Probe Fail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=~\"$job\"} == 0)"
    }
   ]
  },
  {
   "title": "Probes Success Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(probe_success{job=\"blackbox\"} == 1) OR vector(0)) / count(probe_http_version{job=\"blackbox\"})"
    }
   ]
  },
  {
   "title": "Versions TLS",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (version) (probe_tls_version_info{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Site Up/Down Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=~\"$job\"} == 1)",
     "legendFormat": "Success status instance"
    },
    {
     "expr": "count(probe_success{job=~\"$job\"} == 0)",
     "legendFormat": "Failed status instance"
    }
   ]
  },
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "probe_http_version{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SSL going to expire in less than 30 days",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry- time() < (3600 * 24 * 30)"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$instance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Uptime %",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Latest Response Code",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "probe_http_status_code{job=\"blackbox\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "HTTP duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 59 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(probe_http_duration_seconds{job=\"blackbox\", instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "SSL Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "probe_tls_version_info{job=\"blackbox\", instance=~\"$instance\"}",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Redirects",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "probe_http_redirects{job=\"blackbox\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "probe_http_version{job=\"blackbox\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "HTTP phase percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 67 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(probe_http_duration_seconds{job=\"blackbox\", instance=~\"$instance\"}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "SSL Certificate Expiry",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{job=\"blackbox\", instance=~\"$instance\"} - time()"
      }
     ]
    },
    {
     "title": "Average Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "probe_duration_seconds{job=\"blackbox\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "probe_dns_lookup_time_seconds{job=\"blackbox\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}