global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: ap-south-1
        access_key: yourkey
        secret_key: yourkey
        port: 9100
#  - job_name: 'node'
#    static_configs:
#      - targets: ['ip:9100']

