route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
#  group_interval: 60s
# repeat_interval: 1h
  repeat_interval: 15m
  receiver: 'PromeAlerts'
receivers:
    - name: 'PromeAlerts'
      webhook_configs:
      - url: 'http://127.0.0.1:6000/dispatch'
        #      - send_resolved: true
        # - url: 'http://127.0.0.1:6000/create?room_name=PromeAlerts'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

#global:
#  smtp_from: 
#  smtp_smarthost: 
#  smtp_auth_username: 
#  smtp_auth_password:
#templates:
#- '/etc/alertmanager/template/*.tmpl'
#route:
# group_by: ['alertname']
# group_wait: 3s
# group_interval: 5s
# repeat_interval: 1h
#receiver: mail-receiver
#receivers:
#- name: 'mail-receiver'
#email_configs:
#  - to: 'emails of the ones that need to be notified'
#    send_resolved: true

